### ISSUE TITLE
fix time offsets in get_infect_mat.R

### ISSUE THREAD

**Issue by kgrantz** [HopkinsIDD/tti#1]
gamma_qcs <- get_prop_infect_time(t_qcs - t_incubation, ...) and similar should use generation time, not incubation period

**Comment by LucyMcGowan** [comment]
I'm not sure what you mean by "generation time not incubation period" - right now `t_qcs - t_incubation` is plugged into the gamma distribution to *get* generation time right?

**Comment by kgrantz** [comment]
The gamma distribution is pdf of infectiousness by t*, time from symptom onset offset by -2.31. 
t_qhs = time from symptom onset *of G0* to quarantine of G1
t* = t_qhs - generation.time = time from symptom onset of G1 to quarantine of G1

**Comment by kgrantz** [comment]
and here, generation time is median (mean?) incubation period + median (mean?) infectiousness, or
5.1 + qgamma(0.5, shape, rate) - 2.31

**Comment by jlessler** [comment]
If we are subtracting single numbers everything should be means, not medians
